Repository FasterXML/jackson-databind, pull requests merged in 2020-10, with the labels that each got.

#2875 Added case sensitivity check flag from MapperConfig to EnumResolver
  release-notes/CREDITS
  release-notes/VERSION
  src/main/java/com/fasterxml/jackson/databind/util/EnumResolver.java
  src/test/java/com/fasterxml/jackson/databind/deser/jdk/EnumDeserializationTest.java
Labels: hacktoberfest, hacktoberfest-accepted

#2889 Adding docs on using Builder pattern #2291
  README.md
Labels: hacktoberfest-accepted

#2891 #2885 hasFractionalPart method added
  src/main/java/com/fasterxml/jackson/databind/JsonNode.java
  src/main/java/com/fasterxml/jackson/databind/node/DecimalNode.java
  src/main/java/com/fasterxml/jackson/databind/node/DoubleNode.java
  src/main/java/com/fasterxml/jackson/databind/node/FloatNode.java
  src/test/java/com/fasterxml/jackson/databind/node/NumberNodesTest.java
Labels: hacktoberfest-accepted

#2902 #2898 adding one more example for builder pattern
  README.md
Labels: hacktoberfest
