Repository FasterXML/jackson-databind, pull requests merged in 2022-10, with the labels that each got.

#3505 Fix deduction deserializer with DefaultTypeResolverBuilder (pending #)
  src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java
  src/test/java/com/fasterxml/jackson/databind/deser/TestDeserializerFactoryWithDefaultTypeResolverBuilder.java
Labels: 2.14

#3620 Added more documentation for Builder
  README.md
Labels: hacktoberfest-accepted

#3621 [2.13.x] Add check in primitive value deserializers to avoid deep wrapper array nesting wrt UNWRAP_SINGLE_VALUE_ARRAYS [CVE-2022-42003]
  release-notes/VERSION-2.x
  src/main/java/com/fasterxml/jackson/databind/deser/std/StdDeserializer.java
  src/test/java/com/fasterxml/jackson/databind/deser/dos/DeepArrayWrappingForDeser3590Test.java
Labels: CVE, 2.13

#3626 Implementation for "Provide method ObjectMapper.copyWith(JsonFactory)" Closes #3212
  src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java
  src/test/java/com/fasterxml/jackson/databind/ObjectMapperTest.java
Labels: hacktoberfest-accepted

#3641 Fix #3633: expose typed instances of standard `PropertyNamingStrategy` instances
  release-notes/CREDITS-2.x
  release-notes/VERSION-2.x
  src/main/java/com/fasterxml/jackson/databind/PropertyNamingStrategies.java
Labels: 2.14
