Repository FasterXML/jackson-databind, pull requests merged in 2023-01, with the labels that each got.

#3716 Fix #3711: type id for DEDUCTION case was not working for scalar values
  release-notes/VERSION-2.x
  src/main/java/com/fasterxml/jackson/databind/jsontype/impl/AsDeductionTypeSerializer.java
  src/main/java/com/fasterxml/jackson/databind/jsontype/impl/StdTypeResolverBuilder.java
  src/test/java/com/fasterxml/jackson/databind/jsontype/TestPolymorphicDeduction.java
Labels: 2.14

#3724 Change Records deserialization to use the same mechanism as POJO deserialization.
  src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java
  src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java
  src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java
  src/main/java/com/fasterxml/jackson/databind/jdk14/JDK14Util.java
  src/test-jdk14/java/com/fasterxml/jackson/databind/records/Jdk8ConstructorParameterNameAnnotationIntrospector.java
  src/test-jdk14/java/com/fasterxml/jackson/databind/records/RecordBasicsTest.java
  src/test-jdk14/java/com/fasterxml/jackson/databind/records/RecordCreatorsTest.java
  src/test-jdk14/java/com/fasterxml/jackson/databind/records/RecordExplicitCreatorsTest.java
  src/test-jdk14/java/com/fasterxml/jackson/databind/records/RecordImplicitCreatorsTest.java
  src/test-jdk14/java/com/fasterxml/jackson/databind/records/RecordNamingStrategy2992Test.java
  src/test-jdk14/java/com/fasterxml/jackson/databind/records/RecordTypeInfo3342Test.java
  src/test-jdk14/java/com/fasterxml/jackson/databind/records/RecordWithJsonIgnoreTest.java
  src/test-jdk14/java/com/fasterxml/jackson/databind/records/RecordWithJsonNaming3102Test.java
  src/test-jdk14/java/com/fasterxml/jackson/databind/records/RecordWithJsonSetter2974Test.java
Labels: 2.15

#3745 Deprecate classes in package jsonschema
  src/main/java/com/fasterxml/jackson/databind/ext/DOMSerializer.java
  src/main/java/com/fasterxml/jackson/databind/jsonschema/JsonSerializableSchema.java
  src/main/java/com/fasterxml/jackson/databind/jsonschema/SchemaAware.java
  src/main/java/com/fasterxml/jackson/databind/ser/DefaultSerializerProvider.java
  src/main/java/com/fasterxml/jackson/databind/ser/impl/StringArraySerializer.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/AsArraySerializerBase.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/BeanSerializerBase.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/BooleanSerializer.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/ByteArraySerializer.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/ClassSerializer.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/DateTimeSerializerBase.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/EnumSerializer.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/FileSerializer.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/JsonValueSerializer.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/MapSerializer.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/NullSerializer.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/NumberSerializer.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/NumberSerializers.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/RawSerializer.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/SqlTimeSerializer.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/StaticListSerializerBase.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/StdArraySerializers.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/StdDelegatingSerializer.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/StdJdkSerializers.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/StdScalarSerializer.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/StdSerializer.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/StringSerializer.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/ToEmptyObjectSerializer.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/ToStringSerializerBase.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/TokenBufferSerializer.java
  src/test/java/com/fasterxml/jackson/databind/jsonschema/NewSchemaTest.java
  src/test/java/com/fasterxml/jackson/databind/module/SimpleModuleTest.java
Labels: 2.15

#3768 Fix : Not thread-safe singleton factory methods on EnumResolver and StdKeyDeserializer class
  src/main/java/com/fasterxml/jackson/databind/deser/std/EnumDeserializer.java
  src/main/java/com/fasterxml/jackson/databind/deser/std/StdKeyDeserializer.java
Labels: cla-needed
