Repository FasterXML/jackson-databind, pull requests merged in 2024-10, with the labels that each got.

#4728 Add more `EnumNamingStrategies`
  release-notes/CREDITS-2.x
  release-notes/VERSION-2.x
  src/main/java/com/fasterxml/jackson/databind/EnumNamingStrategies.java
  src/main/java/com/fasterxml/jackson/databind/PropertyNamingStrategies.java
  src/main/java/com/fasterxml/jackson/databind/util/NamingStrategyImpls.java
  src/test/java/com/fasterxml/jackson/databind/deser/enums/EnumNamingDeserializationTest.java
  src/test/java/com/fasterxml/jackson/databind/introspect/EnumNamingStrategiesTest.java
  src/test/java/com/fasterxml/jackson/databind/ser/jdk/EnumNamingSerializationTest.java
Labels: 2.19, cla-received

#4722 Fix issues 4697 and 2461 (`@JsonUnwrapped` caching)
  release-notes/CREDITS-2.x
  release-notes/VERSION-2.x
  src/main/java/com/fasterxml/jackson/databind/ser/BeanPropertyWriter.java
  src/test/java/com/fasterxml/jackson/databind/tofix/JsonUnwrappedInconsistentSerialization4697Test.java
  src/test/java/com/fasterxml/jackson/databind/tofix/UnwrappedCaching2461Test.java
Labels: 2.19, cla-received

#4723 Badoken/global enum naming strategy
  release-notes/CREDITS-2.x
  release-notes/VERSION-2.x
  src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java
  src/main/java/com/fasterxml/jackson/databind/cfg/BaseSettings.java
  src/main/java/com/fasterxml/jackson/databind/cfg/MapperBuilder.java
  src/main/java/com/fasterxml/jackson/databind/cfg/MapperConfig.java
  src/main/java/com/fasterxml/jackson/databind/cfg/MapperConfigBase.java
  src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java
  src/main/java/com/fasterxml/jackson/databind/introspect/EnumNamingStrategyFactory.java
  src/main/java/com/fasterxml/jackson/databind/ser/std/EnumSerializer.java
  src/test/java/com/fasterxml/jackson/databind/ObjectMapperTest.java
  src/test/java/com/fasterxml/jackson/databind/deser/enums/EnumNamingDeserializationTest.java
Labels: 2.19, cla-received

#4761 Add feature to inverse read/write access logic
  src/main/java/com/fasterxml/jackson/databind/MapperFeature.java
  src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertyBuilder.java
  src/test/java/com/fasterxml/jackson/databind/deser/filter/ReadOrWriteOnlyTest.java
Labels: cla-received

#4768 Minor improvement to overridability of `JsonMappingException`s path reference
  src/main/java/com/fasterxml/jackson/databind/JsonMappingException.java
Labels: 2.18
