Repository FasterXML/jackson-databind, pull requests merged in 2024-06, with the labels that each got.

#4555 Fix #4552: change `MapperFeature.ALLOW_FINAL_FIELDS_AS_MUTATORS` default to `false`
  release-notes/VERSION
  src/main/java/tools/jackson/databind/MapperFeature.java
  src/test/java/tools/jackson/databind/objectid/ObjectId3838Test.java
Labels: 3.x

#4566 Enable `DeserializationFeature.READ_ENUMS_USING_TO_STRING` by default (3.0)
  release-notes/VERSION
  src/main/java/tools/jackson/databind/DeserializationFeature.java
  src/test/java/tools/jackson/databind/deser/creators/EnumCreatorTest.java
  src/test/java/tools/jackson/databind/deser/enums/EnumDefaultReadTest.java
  src/test/java/tools/jackson/databind/deser/enums/EnumDeserFromIntJsonValueTest.java
  src/test/java/tools/jackson/databind/deser/enums/EnumDeserMixin2787Test.java
  src/test/java/tools/jackson/databind/deser/enums/EnumDeserializationTest.java
  src/test/java/tools/jackson/databind/jsontype/deftyping/TestDefaultForObject.java
Labels: 3.x

#4567 Enable `SerializationFeature.WRITE_ENUMS_USING_TO_STRING` by default (3.0)
  release-notes/VERSION
  src/main/java/tools/jackson/databind/SerializationFeature.java
  src/main/java/tools/jackson/databind/jdk14/JDK14Util.java
  src/test/java/tools/jackson/databind/deser/creators/EnumCreatorTest.java
  src/test/java/tools/jackson/databind/deser/enums/EnumMapDeserializationTest.java
  src/test/java/tools/jackson/databind/deser/enums/EnumWithNullToString4355Test.java
  src/test/java/tools/jackson/databind/jsontype/deftyping/TestDefaultForObject.java
  src/test/java/tools/jackson/databind/ser/EnumAsMapKeyTest.java
  src/test/java/tools/jackson/databind/ser/enums/EnumSerializationMixinTest.java
  src/test/java/tools/jackson/databind/ser/jdk/EnumNamingSerializationTest.java
  src/test/java/tools/jackson/databind/ser/jdk/EnumSerializationTest.java
Labels: 3.x

#4572 Change `MapperFeature.SORT_PROPERTIES_ALPHABETICALLY` default to true (3.x)
  release-notes/VERSION
  src/main/java/tools/jackson/databind/MapperFeature.java
  src/test-jdk17/java/tools/jackson/databind/records/RecordCreatorSerialization4452Test.java
  src/test-jdk17/java/tools/jackson/databind/records/RecordExplicitCreatorsTest.java
  src/test-jdk17/java/tools/jackson/databind/records/RecordSerializationOrderTest.java
  src/test-jdk17/java/tools/jackson/databind/records/RecordWithView4085Test.java
  src/test/java/tools/jackson/databind/jsontype/ExistingPropertyTest.java
  src/test/java/tools/jackson/databind/ser/SerializationOrderTest.java
Labels: 3.x

#4583 Fix #4407: support use of `null` typeId by custom TypeIdResolver
  release-notes/VERSION-2.x
  src/main/java/com/fasterxml/jackson/databind/jsontype/impl/AsArrayTypeDeserializer.java
  src/main/java/com/fasterxml/jackson/databind/jsontype/impl/TypeSerializerBase.java
  src/test/java/com/fasterxml/jackson/databind/jsontype/CustomTypeIdResolver4407Test.java
Labels: 2.18

#4587 Fix #4580: add `MapperFeature.SORT_CREATOR_PROPERTIES_BY_DECLARATION_ORDER`
  release-notes/VERSION-2.x
  src/main/java/com/fasterxml/jackson/databind/MapperFeature.java
  src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java
  src/test-jdk17/java/com/fasterxml/jackson/databind/records/RecordPrivate4175Test.java
  src/test-jdk17/java/com/fasterxml/jackson/databind/records/RecordSerializationOrderTest.java
  src/test/java/com/fasterxml/jackson/databind/ser/SerializationOrderTest.java
Labels: 2.18

#4596 Fix #4595: PropertyName.merge() not considering PropertyName.NO_NAME
  release-notes/VERSION-2.x
  src/main/java/com/fasterxml/jackson/databind/PropertyName.java
Labels: 2.17
