Repository FasterXML/jackson-databind, pull requests merged in 2025-04, with the labels that each got.

#5073 Fixing records deserialization issues with read-access when json renamed to same property name
  release-notes/CREDITS-2.x
  release-notes/VERSION-2.x
  src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java
  src/test-jdk17/java/com/fasterxml/jackson/databind/records/RecordWithJsonIgnoreTest.java
  src/test-jdk17/java/com/fasterxml/jackson/databind/records/RecordWithReadOnlyTest.java
  src/test-jdk17/java/com/fasterxml/jackson/databind/tofix/RecordWIthJsonIgnoreAndValue4628Test.java
  src/test-jdk17/java/com/fasterxml/jackson/databind/tofix/RecordWithReadOnly5049Test.java
Labels: 2.18

#5077 Fixes #5065: default change for `DateTimeFeature.ONE_BASED_MONTHS`
  release-notes/VERSION
  src/main/java/tools/jackson/databind/cfg/DateTimeFeature.java
  src/main/java/tools/jackson/databind/cfg/MapperBuilder.java
  src/main/java/tools/jackson/databind/ext/javatime/JavaTimeInitializer.java
  src/main/java/tools/jackson/databind/ext/javatime/deser/JavaTimeDeserializerModifier.java
  src/main/java/tools/jackson/databind/ext/javatime/deser/OneBasedMonthDeserializer.java
  src/main/java/tools/jackson/databind/ext/javatime/ser/JavaTimeSerializerModifier.java
  src/main/java/tools/jackson/databind/ext/javatime/ser/OneBasedMonthSerializer.java
  src/test/java/tools/jackson/databind/ext/javatime/DateTimeTestBase.java
  src/test/java/tools/jackson/databind/ext/javatime/deser/OneBasedMonthDeserTest.java
Labels: date-time-config, 3.0

#5082 Fixes #3343: make `BeanPropertyWriter.get()` non-final
  release-notes/VERSION-2.x
  src/main/java/com/fasterxml/jackson/databind/ser/BeanPropertyWriter.java
Labels: 2.19

#5099 Fix regression in `ObjectNode.with()`
  release-notes/CREDITS-2.x
  src/main/java/com/fasterxml/jackson/databind/node/ObjectNode.java
  src/test/java/com/fasterxml/jackson/databind/node/ObjectNodeTest.java
Labels: cla-received

#5116 Fixes #4136: drop dangerous deprecated `PropertyNamingStrategy` implementations
  release-notes/VERSION-2.x
  src/main/java/com/fasterxml/jackson/databind/PropertyNamingStrategy.java
Labels: 2.20

#5118 Fix #5103: pass Object size to writeStartObject() for ObjectNode serialization
  release-notes/VERSION-2.x
  src/main/java/com/fasterxml/jackson/databind/node/ObjectNode.java
Labels: 2.20
