Repository FasterXML/jackson-databind, pull requests merged in 2025-05, with the labels that each got.

#5140 Fixed problem in `CollectionDeserializer` where `_nullProvider` was not used if it was not `JsonToken.VALUE_NULL`
  release-notes/CREDITS-2.x
  release-notes/VERSION-2.x
  src/main/java/com/fasterxml/jackson/databind/deser/std/CollectionDeserializer.java
  src/test/java/com/fasterxml/jackson/databind/deser/jdk/CollectionDeserializer5139Test.java
Labels: 2.19

#5135 Fixes #5133: reverts default change of `DeserializationFeature.FAIL_ON_UNEXPECTED_VIEW_PROPERTIES`
  src/main/java/tools/jackson/databind/DeserializationFeature.java
Labels: 3.0, 3.0-release-notes

#5138 add asShort(), asFloat() conversion methods with tests
  src/main/java/tools/jackson/databind/JsonNode.java
  src/main/java/tools/jackson/databind/node/BaseJsonNode.java
  src/main/java/tools/jackson/databind/node/BigIntegerNode.java
  src/main/java/tools/jackson/databind/node/BooleanNode.java
  src/main/java/tools/jackson/databind/node/DecimalNode.java
  src/main/java/tools/jackson/databind/node/DoubleNode.java
  src/main/java/tools/jackson/databind/node/FloatNode.java
  src/main/java/tools/jackson/databind/node/IntNode.java
  src/main/java/tools/jackson/databind/node/LongNode.java
  src/main/java/tools/jackson/databind/node/NullNode.java
  src/main/java/tools/jackson/databind/node/NumericFPNode.java
  src/main/java/tools/jackson/databind/node/NumericIntNode.java
  src/main/java/tools/jackson/databind/node/NumericNode.java
  src/main/java/tools/jackson/databind/node/POJONode.java
  src/main/java/tools/jackson/databind/node/ShortNode.java
  src/main/java/tools/jackson/databind/node/StringNode.java
  src/main/java/tools/jackson/databind/node/ValueNode.java
  src/test/java/tools/jackson/databind/node/JsonNodeDoubleValueTest.java
  src/test/java/tools/jackson/databind/node/JsonNodeFloatValueTest.java
  src/test/java/tools/jackson/databind/node/JsonNodeIntValueTest.java
  src/test/java/tools/jackson/databind/node/JsonNodeLongValueTest.java
  src/test/java/tools/jackson/databind/node/JsonNodeShortValueTest.java
  src/test/java/tools/jackson/databind/node/POJONodeTest.java
Labels: 3.0

#5131 Part of databind#3072: Make @JacksonInject not fail when there's no corresponding value
  release-notes/CREDITS-2.x
  release-notes/VERSION-2.x
  src/main/java/com/fasterxml/jackson/databind/DeserializationContext.java
  src/main/java/com/fasterxml/jackson/databind/DeserializationFeature.java
  src/main/java/com/fasterxml/jackson/databind/InjectableValues.java
  src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializerBuilder.java
  src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializerFactory.java
  src/main/java/com/fasterxml/jackson/databind/deser/CreatorProperty.java
  src/main/java/com/fasterxml/jackson/databind/deser/impl/PropertyValueBuffer.java
  src/main/java/com/fasterxml/jackson/databind/deser/impl/ValueInjector.java
  src/main/java/com/fasterxml/jackson/databind/deser/std/StdValueInstantiator.java
  src/test/java/com/fasterxml/jackson/databind/deser/inject/JacksonInject3072Test.java
  src/test/java/com/fasterxml/jackson/databind/introspect/IntrospectorPairTest.java
  src/test/java/com/fasterxml/jackson/databind/tofix/JacksonInject4218Test.java
Labels: cla-received, 2.20
